### ISSUE TITLE
Basic Push Notification Functionality

### ISSUE THREAD

**Issue by Nezteb** [Nezteb/aurora#1]
Getting push notifications for both iOS and Android is a priority for this project. We need to get even very basic push notifications working.

**Comment by Nezteb** [comment]
So, with this commit: https://github.com/Nezteb/aurora/commit/8e32d7e930f6620afa6683045203c95e993c9c83

We can now initialize the push notification object. Also Mike showed us this:
https://github.com/Nezteb/aurora/blob/a236b14521788157f7f48eb7411cb56609eef1ad/IntelXDK/www/index.html

**Comment by FizzyGalacticus** [comment]
Was able to register device with server and successfully send a notification to my physical device (Google Nexus 6) as well as emulator running Google API's 23 on Google API atom x64.  We need to get APNS stuff setup for testing on iOS devices ASAP.

EMULATOR MUST BE GOOGLE API IMAGE FOR PUSH NOTIFICATIONS TO WORK PROPERLY.

**Comment by awlease** [comment]
We worked on this today until we were able to get it to work on all the Android devices.

**Comment by Nezteb** [comment]
This is mostly done. Now we just have to get Kp triggers working.
