### ISSUE TITLE
Modify/Audit Python Code On Server

### ISSUE THREAD

**Issue by Nezteb** [Nezteb/aurora#10]
The old Python code was "written in a day". We need to go through every bit of code on the server and audit/comment it so that it's easily readable by anyone.

**Comment by Nezteb** [comment]
We may need to change the Python code so that instead of pulling from NOAA (through Soothsayer) we pull from the API that Paul will eventually write.

Although it would be nice to audit the Python code and make it more module and understandable, it is not completely necessary for a minimum viable product at this point because at least it works.

**Comment by Nezteb** [comment]
We're using the GI API now, so this is mostly taken care of.

**Comment by FizzyGalacticus** [comment]
Completely re-wrote server-side code in NodeJS.
