### ISSUE TITLE
Coordinate Interface With GI Designer

### ISSUE THREAD

**Issue by Nezteb** [Nezteb/aurora#11]
We need to speak with the designer at the GI and figure out what aspects of the UI are missing/unnecessary and what design changes are needed.

**Comment by Nezteb** [comment]
We still need designs/sketches/images from Andy. I emailed him.

**Comment by Nezteb** [comment]
We've got everything we need for now from Andy.

**Comment by FizzyGalacticus** [comment]
Andy has given us excellent designs that we have implemented to the best of our ability given time/requirement constraints.
